// Generated by Wrangler by running `wrangler types --env-interface Bindings`

interface Bindings {
	RATE_LIMIT: KVNamespace;
	CACHE: KVNamespace;
	ASSETS: R2Bucket;
	DB: D1Database;
	VECTORIZE: VectorizeIndex;
	AI: Ai;
	FIREBASE_ADMIN_KEY?: string;
	ZEN_API_KEY?: string;
	STRIPE_SECRET_KEY?: string;
	STRIPE_WEBHOOK_SECRET?: string;
	STRIPE_PUBLISHABLE_KEY?: string;
	RESEND_API_KEY?: string;
	SMTP_HOST?: string;
	SMTP_PORT?: string;
	SMTP_USER?: string;
	SMTP_PASS?: string;
	SMTP_FROM?: string;
	SUPPORT_INBOX_EMAIL?: string;
}
