// Generated by Wrangler by running `wrangler types --env-interface Bindings`

interface Bindings {
	RATE_LIMIT: KVNamespace;
	CACHE: KVNamespace;
	ASSETS: R2Bucket;
	DB: D1Database;
	VECTORIZE: VectorizeIndex;
	AI: Ai;
}
